NIC_NAME can be modify by script

diff --git a/funcForDQA/sw_func b/funcForDQA/sw_func
--- a/funcForDQA/sw_func
+++ b/funcForDQA/sw_func
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+NIC_NAME="enp6s0"
+
 LOCAL_DIRECTORY=$(pwd)   
 BASE_DIRECTORY=$(dirname "$(pwd)")
 
@@ -7,12 +9,23 @@ TOOL_DIRECTORY=$BASE_DIRECTORY/UMSD_v7.0.0/host/linux
 PASSWD=ros
 COMMAND=$1
 
+CONFIG_FILE=$LOCAL_DIRECTORY/umsd.cfg
+
+if [ -f "$CONFIG_FILE" ]; then
+   sed -i "s/^[\t ]*nic_name.*/\t\tnic_name $NIC_NAME/" "$CONFIG_FILE"
+   echo "NIC name in the configuration file has been updated"
+else
+   echo "Configuration file "umsd.cfg" not found."
+   echo -e "\nPress Enter to continue..."
+   read  
+   exit 1
+fi
 shift
 
 cd $TOOL_DIRECTORY
 echo "$PASSWD" | sudo -S true
 
-gnome-terminal -- bash -c "echo $PASSWD | sudo -S ./UMSD_MCLI -f $LOCAL_DIRECTORY/umsd.cfg"
+gnome-terminal -- bash -c "echo $PASSWD | sudo -S ./UMSD_MCLI -f $CONFIG_FILE"
 #MCLI_PID=$(echo $PASSWD | sudo -S lsof -i :8888 | grep "LISTEN" | awk '{print $2}')
 echo "$@"
 sleep 1
@@ -42,6 +55,5 @@ esac
 #TELNET_PID=$(echo $PASSWD | sudo -S lsof -i :5202 | grep "telnet" | awk '{print $2}') 
 sleep 2
 sudo lsof -ti :8888 | xargs sudo kill -9
-
 
 exit 0
